baseURL = "https://lightbi-hugo-theme.netlify.app/"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
languageCode = "en-us"
title = "Salicorne.github.io"
theme = "lightbi-hugo"

metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
enableRobotsTXT = true
enableGitInfo = true
summaryLength  = "30"
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
pagerSize = 6

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = false
delayDisqus = true
showRelatedPosts = false
summaryLength  = "9"
lunrSearch = false
gcse = false
lastmod = false
rss = true
pagination = "10"
hideAuthor = true
description="Your can add your website description here."
previewCardImagePlacement = "top"
showPostImage = false

[Params.Author]
  name = "Salicorne"
  website = "https://salicorne.github.io/"
  authorInfo = "Salicorne"
#  authorPostImage = "/img/author-post-img.jpg"
#  email = "sample@gmail.com"
#  facebook = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  twitter = "username"
  linkedin = "timothee.raboeuf"
  github = "Salicorne"
  bluesky = "leSalicorne"
#  threads = "username"
#  gitlab = "username"
#  reddit = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  spotify = "username"
#  paypal = "username"
#  telegram = "username"
#  mastodon = "url"
#  slack = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #500px = "username"
  #kaggle = "username"
  #weibo = "username"
  #xing = "username"
  #bitbucket = "username"
  #soundcloud = "username"
  # codepen = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

# [[menu.main]]
#     name = "Notes"
#     url = "/notes/"
#     weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

# [[menu.main]]
#     name = "Collections"
#     url = "/collections/"
#     weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5


# [sitemap]
#   changefreq = "monthly"
#   priority = 0.5
#   filename = "sitemap.xml"
# 